config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :regions do
    resources :species do
      resources :sightings
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :species, :foreign_key => "region_id"
  validates :name, :presence => true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :specie

  validates :sighting, :presence => true
end

app/models/specie.rb
class Specie < ActiveRecord::Base
  has_and_belongs_to_many :translation_keys
  
  has_many :sightings
  belongs_to :region

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
  end

  def show
    @region = Region.find(params[:id])
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to regions_path
    else
      render :new
    end
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      redirect_to regions_path
    else
      render :edit
    end
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end

  private
    def region_params
      params.require(:region).permit(:name)
    end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors.Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regions/_form.html.erb
<%= render "layouts/errors", :object => @region %>

<%= form_for @region do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit%>
<% end %>

app/views/regions/edit.html.erb
<h1>Edit Region</h1>

<%= render "form"%>

app/views/regions/index.html.erb
<h1>Regions</h1>

<ul>
  <% @regions.each do |region|%>
    <li><%= link_to region.name, region_path(region) %></li>
  <% end %>
</ul>

<%= link_to "New Region", new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render "form" %>

app/views/regions/show.html.erb
<%= @region.name %>

<p><%= link_to "Edit", edit_region_path(@region) %></p>
<p><%= link_to "Delete", region_path(@region), :data => {:confirm => "You sure", :method => "delete"} %></p>
<p><%= link_to "Return to regions", regions_path %></p>